<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "lbo_services_en_ligne"
 *
 * Auto generated by Extension Builder 2014-07-22
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Services en ligne',
	'description' => 'Permet de faire une liste des services disponibles en ligne.',
	'category' => 'plugin',
	'author' => '',
	'author_email' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
            'vhs'   => '1.9.1',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);